import sys
import devices
sys.path.append("../..")

# russian_date_parser = lambda x: datetime.strptime(x, "DD.MM.YYY HH:MM:SS")
devices.nkvv.paste_values_rus = ["Дата создания записи",
                         "Дата сохранения в БД",
                         "U_A1,кВ",
                         "Ia_A1,мА",
                         "Ir_A1,мА",
                         "Tg_A1,%",
                         "C_A1,От",
                         "DeltaTg_A1,%",
                         "DeltaC_A1,%",
                         "U_B1,кВ",
                         "Ia_B1,мА",
                         "Ir_B1,мА",
                         "Tg_B1,%",
                         "C_B1,От",
                         "DeltaTg_B1,%",
                         "DeltaC_B1,%",
                         "U_C1,кВ",
                         "Ia_C1,мА",
                         "Ir_C1,мА",
                         "Tg_C1,%",
                         "C_C1,От",
                         "DeltaTg_C1,%",
                         "DeltaC_C1,%",
                         "U_A2,кВ",
                         "Ia_A2,мА",
                         "Ir_A2,мА",
                         "Tg_A2,%",
                         "C_A2,От",
                         "DeltaTg_A2,%",
                         "DeltaC_A2,%",
                         "U_B2,кВ",
                         "Ia_B2,мА",
                         "Ir_B2,мА",
                         "Tg_B2,%",
                         "C_B2,От",
                         "DeltaTg_B2,%",
                         "DeltaC_B2,%",
                         "U_C2,кВ",
                         "Ia_C2,мА",
                         "Ir_C2,мА",
                         "Tg_C2,%",
                         "C_C2,От",
                         "DeltaTg_C2,%",
                         "DeltaC_C2,%",
                         "Tair,°С",
                         "Tdevice,°С",
                         "Tcpu,°С",
                         "Freq,Гц",
                         ""]
devices.nkvv.paste_values_utf8 = ['\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u043f\u0438\u0441\u0438',
                          '\u0414\u0430\u0442\u0430 \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0432 \u0411\u0414',
                          'U_A1,\u043a\u0412',
                          'Ia_A1,\u043c\u0410',
                          'Ir_A1,\u043c\u0410',
                          'Tg_A1,%',
                          'C_A1,\u043f\u0424',
                          'DeltaTg_A1,%',
                          'DeltaC_A1,%',
                          'U_B1,\u043a\u0412',
                          'Ia_B1,\u043c\u0410',
                          'Ir_B1,\u043c\u0410',
                          'Tg_B1,%',
                          'C_B1,\u043f\u0424',
                          'DeltaTg_B1,%',
                          'DeltaC_B1,%',
                          'U_C1,\u043a\u0412',
                          'Ia_C1,\u043c\u0410',
                          'Ir_C1,\u043c\u0410',
                          'Tg_C1,%',
                          'C_C1,\u043f\u0424',
                          'DeltaTg_C1,%',
                          'DeltaC_C1,%',
                          'U_A2,\u043a\u0412',
                          'Ia_A2,\u043c\u0410',
                          'Ir_A2,\u043c\u0410',
                          'Tg_A2,%',
                          'C_A2,\u043f\u0424',
                          'DeltaTg_A2,%',
                          'DeltaC_A2,%',
                          'U_B2,\u043a\u0412',
                          'Ia_B2,\u043c\u0410',
                          'Ir_B2,\u043c\u0410',
                          'Tg_B2,%',
                          'C_B2,\u043f\u0424',
                          'DeltaTg_B2,%',
                          'DeltaC_B2,%',
                          'U_C2,\u043a\u0412',
                          'Ia_C2,\u043c\u0410',
                          'Ir_C2,\u043c\u0410',
                          'Tg_C2,%',
                          'C_C2,\u043f\u0424',
                          'DeltaTg_C2,%',
                          'DeltaC_C2,%',
                          'Tair,�\u0421',
                          'Tdevice,�\u0421',
                          'Tcpu,�\u0421',
                          'Freq,\u0413\u0446',
                          'Unnamed: 48']
devices.nkvv.paste_values_rus_dict = {0: ['Дата создания записи', 'datetime', 'overall', 'no_voltage', 'time', 'time_of_measure', 'time_no_voltage'],
                              1: ['Дата сохранения в БД', 'datetime', 'overall', 'no_voltage', 'save', 'time_of_saving', 'save_no_voltage'],
                              2: ['U_A1,кВ', 'voltage', 'A1', 'HV', 'U', 'voltage_difference', 'U_HV'],
                              3: ['Ia_A1,мА', 'power', 'A1', 'HV', 'Ia', 'power_active', 'Ia_HV'],
                              4: ['Ir_A1,мА', 'power', 'A1', 'HV', 'Ir', 'power_reactive', 'Ir_HV'],
                              5: ['Tg_A1,%', 'percentage', 'A1', 'HV', 'tg', 'tangent', 'tg_HV'],
                              6: ['C_A1,пФ', 'other', 'A1', 'HV', 'C', 'c_deviation', 'C_HV'],
                              7: ['DeltaTg_A1,%', 'percentage', 'A1', 'HV', '∆tg', 'tangent_delta', '∆tg_HV'],
                              8: ['DeltaC_A1,%', 'percentage', 'A1', 'HV', '∆C', 'c_delta', '∆C_HV'],
                              9: ['U_B1,кВ', 'voltage', 'B1', 'HV', 'U', 'voltage_difference', 'U_HV'],
                              10: ['Ia_B1,мА', 'power', 'B1', 'HV', 'Ia', 'power_active', 'Ia_HV'],
                              11: ['Ir_B1,мА', 'power', 'B1', 'HV', 'Ir', 'power_reactive', 'Ir_HV'],
                              12: ['Tg_B1,%', 'percentage', 'B1', 'HV', 'tg', 'tangent', 'tg_HV'],
                              13: ['C_B1,пФ', 'other', 'B1', 'HV', 'C', 'c_deviation', 'C_HV'],
                              14: ['DeltaTg_B1,%', 'percentage', 'B1', 'HV', '∆tg', 'tangent_delta', '∆tg_HV'],
                              15: ['DeltaC_B1,%', 'percentage', 'B1', 'HV', '∆C', 'c_delta', '∆C_HV'],
                              16: ['U_C1,кВ', 'voltage', 'C1', 'HV', 'U', 'voltage_difference', 'U_HV'],
                              17: ['Ia_C1,мА', 'power', 'C1', 'HV', 'Ia', 'power_active', 'Ia_HV'],
                              18: ['Ir_C1,мА', 'power', 'C1', 'HV', 'Ir', 'power_reactive', 'Ir_HV'],
                              19: ['Tg_C1,%', 'percentage', 'C1', 'HV', 'tg', 'tangent', 'tg_HV'],
                              20: ['C_C1,пФ', 'other', 'C1', 'HV', 'C', 'c_deviation', 'C_HV'],
                              21: ['DeltaTg_C1,%', 'percentage', 'C1', 'HV', '∆tg', 'tangent_delta', '∆tg_HV'],
                              22: ['DeltaC_C1,%', 'percentage', 'C1', 'HV', '∆C', 'c_delta', '∆C_HV'],
                              23: ['U_A2,кВ', 'voltage', 'A2', 'MV', 'U', 'voltage_difference', 'U_MV'],
                              24: ['Ia_A2,мА', 'power', 'A2', 'MV', 'Ia', 'power_active', 'Ia_MV'],
                              25: ['Ir_A2,мА', 'power', 'A2', 'MV', 'Ir', 'power_reactive', 'Ir_MV'],
                              26: ['Tg_A2,%', 'percentage', 'A2', 'MV', 'tg', 'tangent', 'tg_MV'],
                              27: ['C_A2,пФ', 'other', 'A2', 'MV', 'C', 'c_deviation', 'C_MV'],
                              28: ['DeltaTg_A2,%', 'percentage', 'A2', 'MV', '∆tg', 'tangent_delta', '∆tg_MV'],
                              29: ['DeltaC_A2,%', 'percentage', 'A2', 'MV', '∆C', 'c_delta', '∆C_MV'],
                              30: ['U_B2,кВ', 'voltage', 'B2', 'MV', 'U', 'voltage_difference', 'U_MV'],
                              31: ['Ia_B2,мА', 'power', 'B2', 'MV', 'Ia', 'power_active', 'Ia_MV'],
                              32: ['Ir_B2,мА', 'power', 'B2', 'MV', 'Ir', 'power_reactive', 'Ir_MV'],
                              33: ['Tg_B2,%', 'percentage', 'B2', 'MV', 'tg', 'tangent', 'tg_MV'],
                              34: ['C_B2,пФ', 'other', 'B2', 'MV', 'C', 'c_deviation', 'C_MV'],
                              35: ['DeltaTg_B2,%', 'percentage', 'B2', 'MV', '∆tg', 'tangent_delta', '∆tg_MV'],
                              36: ['DeltaC_B2,%', 'percentage', 'B2', 'MV', '∆C', 'c_delta', '∆C_MV'],
                              37: ['U_C2,кВ', 'voltage', 'C2', 'MV', 'U', 'voltage_difference', 'U_MV'],
                              38: ['Ia_C2,мА', 'power', 'C2', 'MV', 'Ia', 'power_active', 'Ia_MV'],
                              39: ['Ir_C2,мА', 'power', 'C2', 'MV', 'Ir', 'power_reactive', 'Ir_MV'],
                              40: ['Tg_C2,%', 'percentage', 'C2', 'MV', 'tg', 'tangent', 'tg_MV'],
                              41: ['C_C2,пФ', 'other', 'C2', 'MV', 'C', 'c_deviation', 'C_MV'],
                              42: ['DeltaTg_C2,%', 'percentage', 'C2', 'MV', '∆tg', 'tangent_delta', '∆tg_MV'],
                              43: ['DeltaC_C2,%', 'percentage', 'C2', 'MV', '∆C', 'c_delta', '∆C_MV'],
                              44: ['Tair,°С', 'temperature', 'overall', 'no_voltage', 'tair', 'temperature_of_air', 'tair_no_voltage'],
                              45: ['Tdevice,°С', 'temperature', 'overall', 'no_voltage', 'tdev', 'temperature_of_device', 'tdev_no_voltage'],
                              46: ['Tcpu,°С', 'temperature', 'overall', 'no_voltage', 'tcpu', 'temperature_of_cpu', 'tcpu_no_voltage'],
                              47: ['Freq,Гц', 'frequency', 'overall', 'no_voltage', 'freq', 'frequency', 'freq_no_voltage'],
                              48: ['Unnamed: 48', 'other', 'overall', 'no_voltage', 'no_name', 'no_name', 'no_name_no_voltage']}

devices.kiv.paste_values_rus_dict = {
    0: [' № ', 'other', 'overall', 'no_voltage', 'no_name', 'no_name', 'no_name_no_voltage'],
    1: ['Дата/Время UTC+03:00', 'datetime', 'overall', 'no_voltage', 'time', 'time_of_measure', 'time_no_voltage'],
    2: ['U ф.A', 'voltage', 'A0', 'MV', 'U', 'voltage_difference', 'U_MV'],
    3: ['U ф.B', 'voltage', 'B0', 'MV', 'U', 'voltage_difference', 'U_MV'],
    4: ['U ф.C', 'voltage', 'C0', 'MV', 'U', 'voltage_difference', 'U_MV'],
    5: ['I ф.A', 'power', 'A0', 'MV', 'Ia', 'power_active', 'Ia_MV'],
    6: ['I ф.B', 'power', 'B0', 'MV', 'Ia', 'power_active', 'Ia_MV'],
    7: ['I ф.C', 'power', 'C0', 'MV', 'Ia', 'power_active', 'Ia_MV'],
    8: ['F', 'other', 'overall', 'no_voltage', 'no_name', 'no_name', 'no_name_no_voltage'],
    9: ['U0', 'other', 'overall', 'no_voltage', 'U', 'voltage_difference', 'U_no_voltage'],
    10: ['U1', 'other', 'overall', 'no_voltage', 'U', 'voltage_difference', 'U_no_voltage'],
    11: ['U2', 'other', 'overall', 'no_voltage', 'U', 'voltage_difference', 'U_no_voltage'],
    12: ['I0', 'other', 'overall', 'no_voltage', 'Ia', 'power_active', 'Ia_no_voltage'],
    13: ['I1', 'other', 'overall', 'no_voltage', 'Ia', 'power_active', 'Ia_no_voltage'],
    14: ['I2', 'other', 'overall', 'no_voltage', 'Ia', 'power_active', 'Ia_no_voltage'],
    15: ['C1 ф.A', 'deviation', 'A0', 'MV', 'C', 'c_deviation', 'C_MV'],
    16: ['C1 ф.B', 'deviation', 'B0', 'MV', 'C', 'c_deviation', 'C_MV'],
    17: ['C1 ф.C', 'deviation', 'C0', 'MV', 'C', 'c_deviation', 'C_MV'],
    18: ['tg δ ф.A', 'percentage', 'A0', 'MV', 'tg', 'tangent', 'tg_MV'],
    19: ['tg δ ф.B', 'percentage', 'B0', 'MV', 'tg', 'tangent', 'tg_MV'],
    20: ['tg δ ф.C', 'percentage', 'C0', 'MV', 'tg', 'tangent', 'tg_MV'],
    21: ['∆C ф.A', 'deviation', 'A0', 'MV', '∆C', 'c_delta', '∆C_MV'],
    22: ['∆C ф.B', 'deviation', 'B0', 'MV', '∆C', 'c_delta', '∆C_MV'],
    23: ['∆C ф.C', 'deviation', 'C0', 'MV', '∆C', 'c_delta', '∆C_MV'],
    24: ['∆tg δ ф.A', 'percentage', 'A0', 'MV', '∆tg', 'tangent_delta', '∆tg_MV'],
    25: ['∆tg δ ф.B', 'percentage', 'B0', 'MV', '∆tg', 'tangent_delta', '∆tg_MV'],
    26: ['∆tg δ ф.C', 'percentage', 'C0', 'MV', '∆tg', 'tangent_delta', '∆tg_MV'],
    27: ['Iunb', 'other', 'overall', 'no_voltage', 'Ia', 'power_active', '', '', 'Ia_no_voltage'],
    28: ['Phy_unb', 'other', 'overall', 'no_voltage', '', '', '_no_voltage'],
    29: ['Tmk, °С', 'temperature', 'overall', 'no_voltage', 'tcpu', 'temperature_of_cpu', 'tcpu_no_voltage'],
    30: ['Tamb, °С', 'temperature', 'overall', 'no_voltage', 'tair', 'temperature_of_air', 'tair_no_voltage']}
